add proper Makefile and manpage

diff --git a/common/hosts_update b/common/hosts_update
--- a/common/hosts_update
+++ b/common/hosts_update
@@ -1,6 +1,10 @@
 #!/bin/bash
-# Script by Wintervenom
-# https://bbs.archlinux.org/viewtopic.php?id=106367
+
+# /usr/bin/hosts_update version @VERSION@
+#
+# Originally by Wintervenom | https://bbs.archlinux.org/viewtopic.php?id=106367
+# Modified by graysky
+#
 
 # select portions from /etc/rc.d/functions and /usr/bin/makepkg to make stuff pretty
 ALL_OFF="\e[1;0m"
@@ -93,8 +97,8 @@ PREFIX_REG="::"
 PREFIX_HL=" >"
 
 if [ ! -f /etc/hosts.local ]; then
-	echo "You need to create /etc/hosts.local containing the hosts you wish to keep!"
-	exit 0
+	echo "/etc/hosts.local missing; reinstall this pacakge."
+	exit 1
 fi
 
 stat_busy "Getting bad actors list from winhelp2002.mvps.org"
@@ -102,6 +106,7 @@ wget -c -O /tmp/hosts.txt http://winhelp2002.mvps.org/hosts.txt &>/dev/null
 stat_done
 
 stat_busy "Merging and writting /etc/hosts"
+
 # Replace every IP address with 0.0.0.0.
 sed -r -e 's:^([0-9]{1,3}\.){3}[0-9]{1,3}:0.0.0.0:' /tmp/hosts.txt > /tmp/hosts.new.txt
 tail -n+`grep -nF 'Start of entries' /tmp/hosts.new.txt | cut -d':' -f1` /tmp/hosts.new.txt > /tmp/hosts.txt
@@ -109,6 +114,7 @@ tail -n+`grep -nF 'Start of entries' /tmp/hosts.new.txt | cut -d':' -f1` /tmp/ho
 # Write this new list over the system hosts list.  MVPS' line feeds
 # are \n\r; we will be getting rid of those dirty carriage returns.
 # We'll first write the user's hosts head, then the black list.
+
 cat /etc/hosts.local > /etc/hosts
 cat /tmp/hosts.txt | tr -d "\r" >> /etc/hosts
 rm /tmp/hosts*.txt
