New: tmpfiles and variale file names hosts_*

diff --git a/common/hosts-update.in b/common/hosts-update.in
--- a/common/hosts-update.in
+++ b/common/hosts-update.in
@@ -81,7 +81,7 @@ stat_die() {
 }
 
 msg() {
-	local mesg=$1; shift
+	local mesg="$1"; shift
 	printf "${RED}===>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
 }
 
@@ -114,18 +114,38 @@ fi
 PREFIX_REG="::"
 PREFIX_HL=" >"
 
+# system host files
+HOSTS_ETC="/etc/hosts"
+HOSTS_LOCAL="/etc/hosts.local"
+
+# temp store downloaded hosts list
+HOSTS_TMP="$(mktemp /tmp/$$.XXXXXXXX)"
+
+# Bad actors host list
+HOSTS_URL="http://winhelp2002.mvps.org/hosts.txt"
+
 process() {
+	local hosts_zeros="$(mktemp /tmp/$$.XXXXXXXX)"
+	local hosts_processed="$(mktemp /tmp/$$.XXXXXXXX)"
+
 	# Replace every IP address with 0.0.0.0.
-	sed -E 's:^([0-9]{1,3}\.){3}[0-9]{1,3}:0.0.0.0:' /tmp/hosts.txt > /tmp/hosts.zeros.txt
-	# TODO: fix this, maybe change to head. Currently gets the first n-x lines where x is the number of lines gotten from the sub-command.
-	tail -n+$(grep -nF 'Start of entries' /tmp/hosts.zeros.txt | cut -d':' -f1) /tmp/hosts.zeros.txt > /tmp/hosts.processed.txt
+	sed -E 's:^([0-9]{1,3}\.){3}[0-9]{1,3}:0.0.0.0:' "$HOSTS_TMP" > "$hosts_zeros"
+
+	# TODO: fix this, maybe change to head. Currently gets the first n-x lines
+	# where x is the number of lines gotten from the sub-command.
+	tail -n+$(grep -nF 'Start of entries' "$hosts_zeros" | cut -d':' -f1) \
+	    "$hosts_zeros" > "$hosts_processed"
+
 	# Write this new list over the system hosts list.  MVPS' line feeds
 	# are \n\r; we will be getting rid of those dirty carriage returns.
 	# We'll first write the user's hosts head, then the black list.
 
-	cat /etc/hosts.local > /etc/hosts
-	cat /tmp/hosts.processed.txt | tr -d "\r" >> /etc/hosts
-	rm /tmp/hosts*.txt
+	cat "$HOSTS_LOCAL" > "$HOSTS_ETC"
+	cat "$hosts_processed" | tr -d "\r" >> "$HOSTS_ETC"
+
+	# Delete temp files
+	rm "$hosts_zeros"
+	rm "$hosts_processed"
 }
 
 if [[ $EUID -ne 0 ]]; then
@@ -133,15 +153,21 @@ if [[ $EUID -ne 0 ]]; then
 	exit 1
 fi
 
-if [[ ! -f /etc/hosts.local ]]; then
-	echo -e ${BOLD}"/etc/hosts.local missing; reinstall this package."${ALL_OFF}
+if [[ ! -f "$HOSTS_LOCAL" ]]; then
+	echo -e ${BOLD}"$HOSTS_LOCAL missing; reinstall this package."${ALL_OFF}
 	exit 1
 fi
 
-stat_busy "Getting bad actors list from winhelp2002.mvps.org"
-curl -C - -s http://winhelp2002.mvps.org/hosts.txt > /tmp/hosts.txt
+stat_busy "Getting bad actors list from $HOSTS_URL"
+curl -C - -s "$HOSTS_URL" > "$HOSTS_TMP"
 [[ $? -gt 0 ]] && stat_die || stat_done
 
-stat_busy "Merging and writting /etc/hosts"
+stat_busy "Merging and writting $HOSTS_ETC"
 process
 [[ $? -gt 0 ]] && stat_die || stat_done
+
+stat_busy "Deleting temp files"
+rm "$HOSTS_TMP"
+[[ $? -gt 0 ]] && stat_die || stat_done
+
+exit $?
