better failure output

diff --git a/common/hosts-update.in b/common/hosts-update.in
--- a/common/hosts-update.in
+++ b/common/hosts-update.in
@@ -67,6 +67,35 @@ stat_done() {
 	printf "   ${C_OTHER}[${C_DONE}DONE${C_OTHER}]${C_CLEAR} \n"
 }
 
+stat_fail() {
+	deltext
+	printf "   ${C_OTHER}[${C_FAIL}FAIL${C_OTHER}]${C_CLEAR} \n"
+}
+
+stat_die() {
+	stat_fail
+	exit ${1:-1}
+}
+
+msg() {
+	local mesg=$1; shift
+	printf "${RED}===>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+process() {
+	# Replace every IP address with 0.0.0.0.
+	sed -r -e 's:^([0-9]{1,3}\.){3}[0-9]{1,3}:0.0.0.0:' /tmp/hosts.txt > /tmp/hosts.new.txt
+	tail -n+`grep -nF 'Start of entries' /tmp/hosts.new.txt | cut -d':' -f1` /tmp/hosts.new.txt > /tmp/hosts.txt
+
+	# Write this new list over the system hosts list.  MVPS' line feeds
+	# are \n\r; we will be getting rid of those dirty carriage returns.
+	# We'll first write the user's hosts head, then the black list.
+
+	cat /etc/hosts.local > /etc/hosts
+	cat /tmp/hosts.txt | tr -d "\r" >> /etc/hosts
+	rm /tmp/hosts*.txt
+}
+
 # set colors
 if tput setaf 0 &>/dev/null; then
 	C_CLEAR=$(tput sgr0)                      # clear text
@@ -96,26 +125,20 @@ fi
 PREFIX_REG="::"
 PREFIX_HL=" >"
 
-if [ ! -f /etc/hosts.local ]; then
-	echo "/etc/hosts.local missing; reinstall this pacakge."
+if [[ $EUID -ne 0 ]]; then
+	echo -e ${BOLD}"This script must be called as root!"${ALL_OFF}
+	exit 1
+fi
+
+if [[ ! -f /etc/hosts.local ]]; then
+	echo -e ${BOLD}"/etc/hosts.local missing; reinstall this pacakge."${ALL_OFF}
 	exit 1
 fi
 
 stat_busy "Getting bad actors list from winhelp2002.mvps.org"
 wget -c -O /tmp/hosts.txt http://winhelp2002.mvps.org/hosts.txt &>/dev/null
-stat_done
+[[ $? -gt 0 ]] && stat_die || stat_done
 
 stat_busy "Merging and writting /etc/hosts"
-
-# Replace every IP address with 0.0.0.0.
-sed -r -e 's:^([0-9]{1,3}\.){3}[0-9]{1,3}:0.0.0.0:' /tmp/hosts.txt > /tmp/hosts.new.txt
-tail -n+`grep -nF 'Start of entries' /tmp/hosts.new.txt | cut -d':' -f1` /tmp/hosts.new.txt > /tmp/hosts.txt
-
-# Write this new list over the system hosts list.  MVPS' line feeds
-# are \n\r; we will be getting rid of those dirty carriage returns.
-# We'll first write the user's hosts head, then the black list.
-
-cat /etc/hosts.local > /etc/hosts
-cat /tmp/hosts.txt | tr -d "\r" >> /etc/hosts
-rm /tmp/hosts*.txt
-stat_done
+process
+[[ $? -gt 0 ]] && stat_die || stat_done
